config/routes.rb
Rails.application.routes.draw do

    resources :people do
    
      collection do
         get 'get_departments', to: "people#get_departments"
      end
        resources :reports do
            member do
              get 'get_report' => 'reports#gen_pdf'
            end
            resources :courses do
            end
        end
    end


    resources :colleges do
      resources :departments
    end
    get '/unauthorized' => 'application#unauthorized'
    root 'welcome#index'

    post '/usersearch/' => 'people#usersearch'
    post '/makeadmin' => 'people#makeadmin'
    post '/revokeadmin' => 'people#revokeadmin'
    get '/reports/new' => 'reports#newopenwindow'
    post '/reports/new' => 'reports#createopenwindow'

	  get '/authorize' => 'application#authorize'
    delete '/logout' => 'application#logout'
end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id            :integer          not null, primary key
#  banner_id     :text
#  net_id        :text
#  first_name    :text
#  last_name     :text
#  position      :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  department_id :integer
#

class Person < ApplicationRecord
  rolify

  attr_writer :department_admin

  has_many :reports, :dependent => :destroy
  has_many :grant_principle_investigators
  has_many :publication_coauthors
  belongs_to :department
  belongs_to :college
  validates :first_name, presence: true
  validates :last_name, presence: true
  #should have no spaces in the net_id
  validates :net_id, presence: true, format: { without: /\s/ }, uniqueness: true
  #banner_id should only have numbers in it
  validates :banner_id, presence: true, numericality: {only_integer: true}, uniqueness: true

  def department_admin
    @department_admin || false
  end
  def full_name
    "#{first_name} #{last_name}"
  end
  def full_name_reversed
    "#{last_name}, #{first_name}"
  end  

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
    
    after_action :verify_authorized, except: :usersearch and :index  

    def index
      authorize :person
      @q = Person.ransack(params[:q])
      @people = @q.result(distinct: true)

    end
    def show
        @person = Person.find(params[:id])
        authorize :person
    end
    def new
        @person = Person.new
        authorize :person
    end
    def edit
        @person = Person.find(params[:id])
        authorize :person
    end
    def create
      @person = Person.new(person_params) 
      @person.department = Department.find(person_params[:department_id])
      @person.add_role(:user, Department.find(person_params[:department_id]))
      authorize :person
      if @person.save
            render json: { success: true, person: @person }
      end
    end

    def update
        @person = Person.find(params[:id])
        authorize :person
    end
    def destroy
        @person = Person.find(params[:id])
        authorize :person
        @person.destroy
        render json: { success: true} 
    end
    def usersearch
      q = params[:query]
      d = Department.find params[:department_id]
      if d.name == "Deans Office"
        c = d.college
        c_id = c.id
        p = Person.where(college_id: c_id).where("lower(last_name) LIKE lower('%#{q}%')")
      else  
        p = Person.where(department_id: params[:department_id]).where("lower(last_name) LIKE lower('%#{q}%')")
      end
       p.each do |p|
        if p.has_role? :department_admin, d
          p.department_admin = true
        end
      end
      render json: p, methods: :department_admin
    end
    def makeadmin
      p = Person.find(params[:person_id])
      d = Department.find(params[:department_id])
      authorize :person 
      if d.name == "Deans Office"
        p.add_role(:department_admin, d.college)
      else
        p.add_role(:department_admin, d)
      end
      render json: { success: true, person: p }
    end
    def revokeadmin
      p = Person.find(params[:person_id])
      d = Department.find(params[:department_id])
      c = d.college
      authorize :person
      p.remove_role(:department_admin, d)
      if d.name == "Deans Office"
        p.remove_role(:department_admin, c)
      end
      p.reload
      
      if (p.has_role? :department_admin, d) || (p.has_role? :department_admin, c)
         render json: { success: false }
      else
         render json: { success: true }
      end
    end

    #used to update department drop-down list when college selection is changed (may no longer be needed)
    def get_departments
       @colleges = College.all
       @college = College.find(params[:college_id])
       @departments = @college.departments   
    end

    private
      def person_params
          params.require(:person).permit(:query, :first_name, :last_name, :net_id, :banner_id, :position, :colleges_id, :college_id, :department_id)
     end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for @person do |f| %>
 
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@person.errors.count, "error") %> prohibited
        this person from being saved:
      </h2>
      <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
 <div class = "field"><p>
    <%= f.label :first_name, 'First Name' %><br>
    <%= f.text_field :first_name %>
  </p></div>
 
  <div class = "field"><p>
    <%= f.label :last_name, 'Last Name' %><br>
    <%= f.text_field :last_name %>
  </p></div>
   <div class = "field"> <p>
    <%= f.label :net_id, 'NetID' %><br>
    <%= f.text_field :net_id %>
  </p></div>
  <div class = "field"><p>
    <%= f.label :banner_id, 'Banner ID (UNM ID #)' %><br>
    <%= f.text_field :banner_id %>
  </p></div>
  <div class = "field"><p>
    <%= f.label :college_id, 'College' %><br>
    <%= f.collection_select :college_id, College.order(:name), :id, :name, {:prompt => "Select a College"}, include_blank: true %>
  </p></div>
  <div class = "field"><p>
    <%= f.label :department_id, 'Department' %><br>
    <%= f.grouped_collection_select :department_id, College.order(:name), :departments, :name, :id, :name, include_blank: true %>
  </p></div>
  <div class = "field"><p>
    <%= f.label :position %><br>
    <%= collection_radio_buttons(:person, :position, Person.positions, :first, :first) do |b| 
            b.label(:"data-value" => b.value) {b.radio_button+b.text.titleize}
        end %> 
  </p></div>
   
  <div class = "actions"><p>
    <%= f.submit class: 'btn btn-primary' %>
  </p></div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>
<%= render 'form' %> 
<%= link_to 'Cancel', people_path, class: "btn btn-warning btn-md" %>

app/views/people/get_departments.js.erb
$('.department_selection').empty();
$('.department_selection').append( $('<option>Select the Department</option>'));
<% @departments.each do |department| %>
   $('.department_select').append($('<option value="<%= department.id %>"><%= department.name %></option>'));
<% end %>

app/views/people/index.html.erb
<h1>Registered People</h1>

<table>
    <tr>
        <th style="padding-right:13px">Last Name</th>
        <th style="padding-right:10px">First Name</th>
        <th style="padding-right:10px">NetID</th>
        <th style="padding-right:9px">Banner ID#</th>
        <th style="padding-right:11px">Position</th>
        <th style="padding-right:50px">College/School</th>
        <th>Department</th>
        <th colspan="2"></th>
    </tr>

    <%= search_form_for @q do |f| %>


      <%= f.label :name %>
      <%= f.search_field :first_name_or_last_name_cont %>
      <%= f.submit %>
    <% end %>


    <% @people.order(:last_name, :first_name) %>
    <% @people.each do |person| %>
        <tr>
            <td><%= person.last_name %></td>
            <td><%= person.first_name %></td>
            <td><%= person.net_id %></td>
            <td><%= person.banner_id %></td>
            <td><%= person.position.titleize %></td>
            <td><%= College.find(person.college_id).name %></td>
            <td><%= person.department.name %></td>

            <td style="padding-left:8px"><%= link_to 'Show', person_path(person), class: "btn btn-outline-primary" %></td>
            <td><%= link_to 'Edit', edit_person_path(person), class: "btn btn-outline-warning" %></td>
            <td><%= link_to 'Delete', person_path(person), class: "btn btn-outline-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
</table>
<%= link_to 'New Person', new_person_path, class: "btn btn-outline-primary" %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>
<%= link_to 'Cancel', people_path, class: "btn btn-warning btn-md" %>

app/views/people/show.html.erb
<div class="container form-section">
  <div class="row">
    <div class="col-sm-4">
      <strong>Name:</strong>
      <%= "#{@person.first_name} #{@person.last_name}" %>
    </div>
    <div class="col-sm-4">
      <strong>Net ID:</strong>
      <%= @person.net_id %>
    </div>
    <div class="col-sm-4">
      <strong>Banner ID:</strong>
      <%= @person.banner_id %>
    </div>
    <div class="col-sm-4">
      <strong>College/School:</strong>
      <%= College.find(@person.college_id).name %>
    </div>
    <div class="col-sm-4">
      <strong>Department:</strong>
      <%= @person.department.name %>
    </div>
    <div class="col-sm-4">
      <strong>Position:</strong>
      <%= @person.position %>
    </div>
  </div>


  <h2>Completed Annual Evaluations</h2>
  <% @reports = @person.reports.all %>
  <% @reports = @reports.order(report_year: :DESC) %>
  <%= render @reports %>

  <%= link_to 'New Annual Evaluation', new_person_report_path(@person), class: "btn btn-primary btn-md" %><br>
  </br><%= link_to 'Back', people_path, class: "btn btn-info btn-md" %><br>
  </br>
</div>