config/routes.rb
Rails.application.routes.draw do

    resources :people do
    
      collection do
         get 'get_departments', to: "people#get_departments"
      end
        resources :reports do
            member do
              get 'get_report' => 'reports#gen_pdf'
            end
            resources :courses do
            end
        end
    end


    resources :colleges do
      resources :departments
    end
    get '/unauthorized' => 'application#unauthorized'
    root 'welcome#index'

    post '/usersearch/' => 'people#usersearch'
    post '/makeadmin' => 'people#makeadmin'
    post '/revokeadmin' => 'people#revokeadmin'
    get '/reports/new' => 'reports#newopenwindow'
    post '/reports/new' => 'reports#createopenwindow'

	  get '/authorize' => 'application#authorize'
    delete '/logout' => 'application#logout'
end

app/models/department.rb
# == Schema Information
#
# Table name: departments
#
#  id         :integer          not null, primary key
#  name       :string
#  college_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Department < ApplicationRecord
  resourcify
  belongs_to :college
  has_many :people
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  before_action :set_college, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index

    @departments = Department.where(college: params[:college_id])
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
     authorize :person
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)
    @department.college = College.find(params[:college_id])
    render json: { success: @department.save, department: @department }
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    render json: { success: @department.update({name: params[:name]}) }
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    render json: { success: @department.destroy }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    def set_college
      @college = College.find(params[:college_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.permit(:name, :college_id, :id)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_for(department) do |f| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<div id="department">
  <div class="heading">
    <h1><%= @department.college.name %></h1>
    <h3><%= @department.name %></h3>
  </div>
  <hr/>
  <h5>Administrators</h5>
  <% if @department.name == "Deans Office" %>
      <p>These people may edit faculty information within the <%= @department.college.name %></p>
  <% else %>
      <p>These people may edit faculty information within the department</p>
  <% end %>

  <div id="admins">
    <table id="admins-table" class="table table-striped table-bordered">
      <thead>
      <tr>
        <th>Name</th>
        <th>Net ID</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
        <tr v-for="(admin,index) in admins">
          <td>{{admin.last_name + ', ' + admin.first_name}}</td>
          <td>{{admin.net_id}}</td>
          <td v-on:click="prepareRevokeAdmin(admin, index)" class="clickable"><i class="fa fa-ban"></i>&nbsp;Revoke Admin</td>
        </tr>
        <tr>
          <td colspan="3" @click="prepareAddAdmin()" class="clickable heading"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;&nbsp;Add new...</td>
        </tr>
      </tbody>
    </table>
  </div>
  <h5>Faculty</h5>
  <p>These people can create new evaluation submissions</p>
  <div id="people">
    <table id="people-table" class="table table-striped table-bordered">
      <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Net ID</th>
      </tr>
      </thead>

      <tbody>
      <tr v-for="(person,index) in people">
        <td>{{index+1}}</td>
        <td>{{person.last_name + ', ' + person.first_name}}</td>
        <td>{{person.net_id}}</td>
        <td v-on:click="prepareEditUser(person)" class="clickable"><i class="fa fa-pencil-square"></i>&nbsp;Edit Person</td>
        <td v-on:click="prepareRemoveUser(person, index)" class="clickable"><i class="fa fa-trash-o"></i>&nbsp;Remove Person</td>
        
      </tr>
      <tr>
        <td colspan="4" @click="prepareAddUser()" class="clickable heading"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;&nbsp;Add new...</td>
      </tr>
      </tbody>
    </table>
  </div>
  <modal :show="showAddAdminModal" @close="showAddAdminModal=false" size="medium">
    <div class="add-admin-form">
      <label for="add-admin">User search:</label>
      <input v-model="query" id="last-name" type="text" class="form-control" placeholder="Last Name" />
      <button type="submit" class="btn btn-primary" @click="userSearch()">Search</button><span class="alert" style="display:none;margin-left:1em;" id="alert"></span>
      <hr style="padding-bottom:2em"/>
      <div v-for="(result,index) in searchResults">
        <table id="search-results" class="table table-striped">
          <tr v-for="(person,index) in searchResults">
            <td>{{person.last_name + ', ' + person.first_name}}</td>
            <td v-if="!person.department_admin" class="clickable" @click="makePersonDepartmentAdmin(person)"><i class='fa fa-lock' aria-hidden='true'></i>&nbsp;Make Admin</td>
            <td v-if="person.department_admin"><i>already admin</i></td>
          </tr>
        </table>
      </div>
    </div>
  </modal>
  <modal :show="showEditUserModal" @close="showEditUserModal=false" size="large">
      <div class="edit-user-form">
      <label for="first-name">First Name</label>
      <input v-model="personObject.first_name" id="first-name" type="text" class="form-control" placeholder="First Name" />
      <label for="last-name">Last Name</label>
      <input v-model="personObject.last_name" id="last-name" type="text" class="form-control" placeholder="Last Name" />
      <label for="net-id">UNM Net ID</label>
      <input v-model="personObject.net_id" id="net-id" type="text" class="form-control" placeholder="NetID" />
      <label for="banner-id">UNM Banner ID (9 digits)</label>
      <input v-model="personObject.banner_id" id="banner-id" type="text" class="form-control" placeholder="Banner ID" />
      <button @click="editUser()" class="btn btn-primary">Update</button>
    </div>
  </modal>
  <modal :show="showAddUserModal" @close="showAddUserModal=false" size="large">
    <div class="add-user-form">
      <label for="first-name">First Name</label>
      <input v-model="newUser.first_name" id="first-name" type="text" class="form-control" placeholder="First Name" />
      <label for="last-name">Last Name</label>
      <input v-model="newUser.last_name" id="last-name" type="text" class="form-control" placeholder="Last Name" />
      <label for="net-id">UNM Net ID</label>
      <input v-model="newUser.net_id" id="net-id" type="text" class="form-control" placeholder="NetID" />
      <label for="banner-id">UNM Banner ID (9 digits)</label>
      <input v-model="newUser.banner_id" id="banner-id" type="text" class="form-control" placeholder="Banner ID" />
      <button @click="addUser()" class="btn btn-primary">Add</button>
    </div>
  </modal>
  <modal :show="showRevokeAdminPersonModal" @close="showRevokeAdminPersonModal=false" size="small">
    <div class="revoke-user-confirm">
      <div class="modal-header">
         <h3>Revoke Admin Rights</h3>
      </div>
      <div class="modal-body">
        <p> Remove administrative rights for {{personObject.last_name + ', ' + personObject.first_name}}? (This will only apply for <%= @department.name.titleize %>)</p>
      </div> 
      <button @click="revokePersonDepartmentAdmin()" class="btn btn-warning">Revoke Admin</button>
      <button @click="showRevokeAdminPersonModal=false" class="btn btn-info">Cancel</button>
      <div class="admin_alert" style="display:none;margin-left:1em;background-color:#f44336;color:white" id="admin_alert"></div>
    </div>
  </modal>
  <modal :show="showRemovePersonModal" @close="showRemovePersonModal=false" size="small">
    <div class="remove-user-confirm">
      <div class="modal-header">
        <h3>Remove Person</h3>
      </div>
      <div class="modal-body">
        <p>Remove <b>{{personObject.last_name + ', ' + personObject.first_name}}</b>?</p>
        <h4 style="color:red;">Warning: This will remove all associated annual evaluations and cannot be undone!</h4>
      </div>
      <button @click="removePerson()" class="btn btn-danger">Remove Person</button>
      <button @click="showRemovePersonModal=false" class="btn btn-info">Cancel</button>
      <div class="admin_alert" style="display:none;margin-left:1em;background-color:#f44336;color:white" id="admin_alert"></div>
    </div>
  </modal>
</div>
<style>
</style>
<script>
  // Load Modal Component
  <%= render 'components/modal.js' %>

  app = new Vue({
    el: '#department',
    
    data: {
      admins: <%= (Person.with_role(:department_admin, @department)+Person.with_role(:department_admin, @college)).to_json.html_safe %>,
      people: <%= Person.with_role(:user, @department).to_json.html_safe %>,
      searchResults: [],
      query: "",
      showAddAdminModal: false,
      showAddUserModal: false,
      showEditUserModal: false,
      showRevokeAdminPersonModal: false,
      showRemovePersonModal: false,
      newUser: {
        first_name: null,
        last_name: null,
        banner_id: null,
        net_id: null,
        department_id: null,
        college_id: null
      },
      personObject: {
        first_name: "none",
        last_name: "none",
        banner_id: null,
        net_id: null,
        department_id: null,
        college_id: null
      },
      indexNum: null
    },
    methods: {
      prepareAddAdmin: function() {
        this.query = ""
        this.searchResults = null
        this.showAddAdminModal = true
      },
      userSearch: function() {
        this.searchResults = null
        if (this.query.length >= 2) {
          $.post('/usersearch', {query: this.query, department_id: <%= @department.id %>}).done(function (resp) {
            if (!$.isEmptyObject(resp)) app.searchResults = resp
            else {
              $('#alert').html('No results!').fadeIn(300)
              setTimeout(function () {
                $('#alert').fadeOut(300)
              }, 3000)
            }
          })
        }
        else {
          $('#alert').html('Query too short').fadeIn(300)
          setTimeout(function () {
            $('#alert').fadeOut(300)
          }, 3000)
        }
      },
      prepareRevokeAdmin: function(adminIn, removeIndexIn) {
        app.personObject = adminIn
        app.indexNum = removeIndexIn
        this.showRevokeAdminPersonModal = true
      },
      prepareEditUser: function(personIn) {
        app.personObject = personIn
        this.showEditUserModal = true
      },
      prepareAddUser: function() {
        this.showAddUserModal = true
      },
      prepareRemoveUser: function(personIn, removeIndexIn) {
        app.personObject = personIn
        app.indexNum = removeIndexIn
        this.showRemovePersonModal = true
      },
      makePersonDepartmentAdmin: function (person) {
        $.post('/makeadmin',{
          person_id: person.id,
          department_id: <%= @department.id %>
        }).done(function(resp){
          if (resp.success)
          {
            app.admins.push(resp.person)
            app.searchResults = null
            app.query = ""
            app.showAddAdminModal = false
          }
        })
      },
      revokePersonDepartmentAdmin: function () {
        $.post('/revokeadmin',{
          person_id: app.personObject.id,
          department_id: <%= @department.id %>
        }).done(function(resp){
          if (resp.success)
          {
            app.admins.splice(app.indexNum, 1);
            app.personObject.first_name = "none"
            app.personObject.last_name = "none"
            app.personObject.banner_id = null
            app.personObject.net_id = null
            
            app.showRevokeAdminPersonModal = false
          }
          else
          {
            $('#admin_alert').html('Error removing admin rights. Ensure you have proper permission to perform this action.').fadeIn(300)
            setTimeout(function () {
              $('#admin_alert').fadeOut(300)
            }, 3000)
          }
        })
      },
      removePerson: function () {
        var url = "/people/" + app.personObject.id;
        $.ajax({
           url: url,
           type: 'DELETE',
           data: { "_token": "{{ csrf_token() }}" },
           success: function(resp) {
             console.log(resp)
             app.people.splice(app.indexNum, 1);
             app.showRemovePersonModal = false
           },
           error: function() {
           $('#admin_alert').html('Error removing user. Ensure you have proper permission to perform this action.').fadeIn(300)
            setTimeout(function () {
              $('#admin_alert').fadeOut(300)
            }, 3000)
           }
        })
      },
      editUser: function() {
        var url = "/people/" + app.personObject.id;
        $.ajax({
           url: url,
           method: 'PUT',
           data: { person: app.personObject },
           success: function(resp) {
             app.showEditUserModal = false
           },
           error: function() {
           $('#admin_alert').html('Error updating user. Ensure you have proper permission to perform this action.').fadeIn(300)
             setTimeout(function () {
               $('#admin_alert').fadeout(300)
             }, 3000)
           }
        })
      },
      addUser: function () {
        this.newUser.department_id = <%= @department.id %>
        this.newUser.college_id = <%= @college.id %>
        $.post("<%= people_path %>",{
          person: this.newUser
          }).done(function(resp){
          if (resp.success)
          {
            console.log(resp)
            app.people.push(resp.person)
            app.newUser.first_name = null
            app.newUser.last_name = null
            app.newUser.banner_id = null
            app.newUser.net_id = null
            app.showAddUserModal = false
          }
        })
      }
    }
  })
  
          
</script>