config/routes.rb
Rails.application.routes.draw do

    resources :people do
    
      collection do
         get 'get_departments', to: "people#get_departments"
      end
        resources :reports do
            member do
              get 'get_report' => 'reports#gen_pdf'
            end
            resources :courses do
            end
        end
    end


    resources :colleges do
      resources :departments
    end
    get '/unauthorized' => 'application#unauthorized'
    root 'welcome#index'

    post '/usersearch/' => 'people#usersearch'
    post '/makeadmin' => 'people#makeadmin'
    post '/revokeadmin' => 'people#revokeadmin'
    get '/reports/new' => 'reports#newopenwindow'
    post '/reports/new' => 'reports#createopenwindow'

	  get '/authorize' => 'application#authorize'
    delete '/logout' => 'application#logout'
end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id                   :integer          not null, primary key
#  report_year          :date
#  rank                 :integer
#  department           :text
#  self_evaluation_text :text
#  future_plans_text    :text
#  person_id            :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  open_time            :datetime         
#  close_time           :datetime
#

class Report < ApplicationRecord
  belongs_to :person
  has_many :courses, :dependent => :destroy, inverse_of: :report
  has_many :university_services, :dependent => :destroy, inverse_of: :report
  has_many :professional_services, :dependent => :destroy, inverse_of: :report
  has_many :outreach_activities, :dependent => :destroy, inverse_of: :report
  has_many :mentees, :dependent => :destroy, inverse_of: :report
  has_many :publications, :dependent => :destroy, inverse_of: :report
  has_many :grants, :dependent => :destroy, inverse_of: :report
  accepts_nested_attributes_for :courses, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :professional_services,reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :university_services, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :outreach_activities, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :publications, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :grants, reject_if: :all_blank, allow_destroy: true 
  accepts_nested_attributes_for :mentees, reject_if: :all_blank, allow_destroy: true
  validates :report_year, presence: true
  validates :department, presence: true
  validates :open_time, presence: true
  validates :close_time, presence: true

  enum rank: [:lecturer, :assistant_professor, :associate_professor, :professor, :distinguished_professor]
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    def index
        @person = Person.find(params[:person_id])
        d = @person.department
        @college = @person.college
        if @person.has_role? :department_admin, d
          p = Person.where(department_id: d)
          @reports =  Report.where(person_id: p)
        elsif @person.has_role? :department_admin, @college
          p = Person.where(college_id: @college)
          @reports = Report.where(person_id: p)
        else
          @reports = @person.reports.all
        end

    end
    def show
        @person = Person.find(params[:person_id])
        @report = @person.reports.find(params[:id])
        @college = College.find(@person.department.college.id)
        @courses = @report.courses.all
        @professional_services = @report.professional_services.all
        @university_services = @report.university_services.all
        @outreach_activities = @report.outreach_activities.all
        @publications = @report.publications.all
        @grants = @report.grants.all
        @mentees = @report.mentees.all
    end
    def new
        @person = Person.find(params[:person_id])
        @department = @person.department
        @report = @person.reports.new
        authorize :report
        @report.courses.build
        @report.professional_services.build
        @report.university_services.build
        @report.outreach_activities.build
        @report.publications.build
        @report.grants.build
        @report.mentees.build

    end
    def edit
        @person = Person.find(params[:person_id])
        @report = @person.reports.find(params[:id])
        authorize :report
    end

    def create
        @person = Person.find(params[:person_id])
        @report = @person.reports.new(report_params)
        authorize :report
        if @report.save!
            respond_to do |format|
                format.html {redirect_to person_path(@person), notice: "Evaluation created successfully." }
            end
        else
            render 'new'
        end
    end

    def update
        @person = Person.find(params[:person_id])
        @report = @person.reports.find(params[:id])
        authorize :report
        if @report.update(report_params)
            redirect_to person_report_path(@person, @report)
        else
            render 'edit'
        end
    end

    def destroy
        
        @person = Person.find(params[:person_id])
        @report = @person.reports.find(params[:id])
        authorize :report
        @report.destroy
        redirect_to person_reports_path(current_user)
    end

    def gen_pdf
        @person = Person.find(params[:person_id])
        @report = @person.reports.find(params[:id])
        @courses = @report.courses.all
        pdf = ReportPdf.new(@person,@report,@courses)
        send_data pdf.render, filename: 'report.pdf', type: 'application/pdf'
    end
    
    def admin_create
        @person = Person.find(params[:person_id])
        authorize :report
    end    
   
   def createopenwindow
        error_tracker = false
        @admin = current_user
        @people = Person.find(params[:people_ids])
        @people.each do |person|
          authorize :report
          @report = person.reports.new
          @report.open_time = DateTime.parse(params[:start] + " 00:00")
          @report.close_time = DateTime.parse(params[:end] + " 23:59")
          if(@report.open_time > @report.close_time)
            error_tracker = true
            flash[:alert] = "Closing date must be later than opening date."
            redirect_to person_reports_path(@admin)
          end
          @report.report_year = '2017-1-1'.to_date
          @report.department = person.department.name
          @report.rank = 'lecturer'
          @report.save 
          if @report.valid? == false
            error_tracker = true 
          end
        end
        if error_tracker
          flash[:alert] = "Error creating new reporting window."
          redirect_to person_reports_path(@admin)  
        else
          redirect_to person_reports_path(@admin)
        end
        
   end

   def newopenwindow
       @person = current_user
       @department = @person.department
 
   end

    private
        def report_params
            params.require(:report).permit(:report_year, :rank, :department, :self_evaluation_text, :future_plans_text, :start, :end, courses_attributes: [:course_number, :course_title, :enrollment, :year, :semester, :evaluation_results, :taught, :report_id, :id, :_destroy], professional_services_attributes: [:id, :title, :description, :type, :report_id, :_destroy], university_services_attributes: [:position, :description, :id, :report_id, :_destroy], outreach_activities_attributes: [:name, :description, :id, :report_id, :_destroy], publications_attributes: [:id, :publication_type, :body, :url, :report_id, :_destroy], grants_attributes: [:status, :id, :title, :duration, :total_funding, :unm_portion, :soe_portion, :granscol, :report_id, :_destroy], mentees_attributes: [:id, :mentee_type, :first_name, :last_name, :middle_name, :banner_id, :study_stage, :expected_graduation, :support_source, :placement, :report_id, :_destroy], people_attributes: [:person_id, :banner_id, :net_id, :first_name, :last_name, :college_id, :department_id ])
        end
end

app/helpers/reports_helper.rb
module ReportsHelper
    def setup_report(report)
        report.courses ||= Course.new
        report
    end
end

app/views/reports/_course_fields.html.erb
<div class="nested-fields form-section container">
  <div class="form-group">
    <div class="row">
      <div class="col-xs-12">
        <%= f.label :course_title, 'Course Title' %><br>
        <%= f.text_field :course_title, class: 'form-control' %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-3">
        <%= f.label :course_number, 'Course Number' %><br>
        <%= f.text_field :course_number, class: 'form-control' %>
      </div>
      <div class="col-xs-3">
        <%= f.label :enrollment, 'Number Enrolled' %><br>
        <%= f.text_field :enrollment, class: 'form-control' %>
      </div>
      <div class="col-xs-3">
        <%= f.label :year %><br>
        <%= f.date_select :year, :start_year => Date.today.year, :end_year => Date.today.year - 5, :discard_day => true, :discard_month => true, :include_blank => false, :with_css_classes => true  %>
      </div>
      <div class="col-xs-3">
        <%= f.label :semester %><br>
        <%= f.text_field :semester, class: 'form-control'  %>
      </div>
    </div>





      <%= f.label :evaluation_results, 'Evaluation Results' %><br>
      <%= f.text_area :evaluation_results, class: 'form-control'  %>

      <%= f.label :taught, 'Taught Class?' %><br>
      <%= f.check_box :taught?, class: 'form-control', 'data-toggle' => 'toggle'   %>
  </div>
    <%= link_to_remove_association "Remove Course Info", f %>
</div>

app/views/reports/_form.html.erb
<%= form_for [@person,@report]  do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@report.errors.count, "error") %> prohibited
        this evaluation from being saved:
      </h2>
      <ul>
        <% @report.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-section container">
      <div class="form-group">
        <div class="row">
          <div class="col-sm-2">
            <%= f.label :report_year, 'Evaluation Year' %>
            <%= f.date_select :report_year,  :discard_day => true, :discard_month => true,:start_year => Date.today.year + 1, :end_year => Date.today.year - 3, :include_blank => false, :with_css_classes => true %>
          </div>
          <div class="col-sm-4">
            <%= f.label :rank %>
            <%= f.select :rank, Report.ranks.keys.map{|rank| [rank.titleize,rank]},{} , {class: 'form-control', style: 'margin-top: .5em'}%>
          </div>
          <div class="col-sm-4">
            <%= f.label :department %>
            <%= f.text_field :department, class: 'form-control', value: current_user.department.name %>
          </div>
        </div>
      </div>
  </div>
  <div>
        <h3>Scholarly Activities:</h3>
        <i>Note: Provide full citations for any of the papers listed below.  Include only items associated with the calendar year identified on this report.</i>
        <div id="Publications">
            <%= f.fields_for :publications do |publication| %>
                <%= render 'publication_fields', f: publication %>
            <% end %>
            <div class="links">
                <%= link_to_add_association 'Add New Publication', f, :publications, class: 'btn btn-outline-primary' %>
            </div>
        </div>
    </div>
    <div>
        <h3>Course Information:</h3>
        <div id="Courses">
            <%= f.fields_for :courses do |course| %>
                <%= render 'course_fields', f: course %>
            <% end %>
            <div class="links">
                 <%= link_to_add_association 'Add New Course', f, :courses, class: 'btn btn-outline-primary' %>
            </div>
        </div>
    </div>
    <div>
        <h3>Professional Service:</h3>
        <div id="Professional Services">
            <%= f.fields_for :professional_services do |professional_service| %>
                <%= render 'professional_service_fields', f: professional_service %>
            <% end %>
            <div class="links">
                <%= link_to_add_association 'Add New Professional Service', f, :professional_services, class: 'btn btn-outline-primary' %>
            </div>
        </div>
    </div>
    <div>
        <h3>University Service:</h3>
        <div id="University Services">
            <%= f.fields_for :university_services do |university_service| %>
                <%= render 'university_service_fields', f: university_service %>
            <% end %>
            <div class="links">
                <%= link_to_add_association 'Add New University Service Position', f, :university_services, class: 'btn btn-outline-primary' %>
            </div>
        </div>
    </div>
    <div>
        <h3>Outreach Activities:</h3>
        <div id="Outreach Activites">
            <%= f.fields_for :outreach_activities do |outreach_activity| %>
                <%= render 'outreach_activity_fields', f: outreach_activity %>
            <% end %>
            <div class="links">
                <%= link_to_add_association 'Add New Outreach Activity', f, :outreach_activities, class: 'btn btn-outline-primary' %>
            </div>
        </div>
    </div>
    <div>
        <h3>Grants:</h3>
        <div id="Grants">
            <%= f.fields_for :grants do |grant| %>
                <%= render 'grant_fields', f: grant %>
            <% end %>
            <div class="links">
                <%= link_to_add_association 'Add New Grant', f, :grants, class: 'btn btn-outline-primary' %>
            </div>
        </div>
    </div>

    <div>
        <h3>Research Mentoring</h3>
        <i>Note:  Do not list the same student twice—clearly a student who just graduated was actually supervised.   When a student is co-supervised, indicate the fact.  Do not include BS and MS students whom you advise, but who are not involved in research.  Indicate placement for graduating students, if known.  Indicate the stage in their studies and the expected graduation date for all students, e.g., pre-qualifier, passed qualified, etc.  Indicate the source of support for the graduate students being supervised.</i>
        <div id="Mentees">
            <%= f.fields_for :mentees do |mentee| %>
                <% render 'mentee_fields', f: mentee %>
            <% end %>
            <div class="links">
                <%= link_to_add_association 'Add New Mentee', f, :mentees, class: 'btn btn-outline-primary' %>
            </div>
        </div>
    </div>
    <div class="form-group">
      <%= f.label :self_evaluation_text, 'Evaluee Self Input' %>
      <%= f.text_area :self_evaluation_text, class: 'form-control' %>

      <%= f.label :future_plans_text, 'Evaluee Future Plans' %>
      <%= f.text_area :future_plans_text, class: 'form-control' %>
    </div>
    <p>
        <%= f.submit class: 'btn btn-primary' %>
    </p>

<% end %>

<script>
$(function(){
  $('input[type="checkbox"]').bootstrapToggle({on: 'Yes', off: 'No', offstyle: 'info'});
})
$(document).on('cocoon:after-insert', function(e, insertedItem) {
  $('input[type="checkbox"]').bootstrapToggle({on: 'Yes', off: 'No', offstyle: 'info'});
})
</script>

app/views/reports/_grant_fields.html.erb
<div class="nested-fields form-section container">
  <div class="form-group">
    <div class="row">
      <div class="col-xs-12">
        <%= f.label :title, 'Grant Title' %><br>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-3">
        <%= f.label :status, 'Grant Status' %><br>
        <%= f.text_field :status, class: 'form-control' %>
      </div>
      <div class="col-xs-3">
        <%= f.label :duration, 'Duration' %><br>
        <%= f.text_field :duration, class: 'form-control' %>
      </div>
      <div class="col-xs-3">
        <%= f.label :total_funding, 'Total Funding ($)' %><br>
        <%= f.text_field :total_funding, class: 'form-control' %>
      </div>
      <div class="col-xs-3">
        <%= f.label :unm_portion, 'UNM Portion of Funding ($)' %><br>
        <%= f.text_field :unm_portion, class: 'form-control'  %>
      </div>
      <div class="col-xs-3">
        <%= f.label :granscol, 'Your College (Name)' %><br>
        <%= f.text_field :granscol, class: 'form-control' %>
      </div>
      <div class="col-xs-3">
        <%= f.label :soe_portion, 'Your College Portion of Funding ($)' %><br>
        <%= f.text_field :soe_portion, class: 'form-control' %>
      </div>
      
    </div>


  </div>
    <%= link_to_remove_association "Remove Grant Info", f %>
</div>

app/views/reports/_mentee_fields.html.erb
<div class="nested-fields form-section container">
  <div class="form-group">
    <div class="row">
      <div class="col-xs-12">
        <%= f.label :mentee_type, 'Mentee Type' %><br>
        <%= f.text_field :mentee_type, class: 'form-control' %>
      </div>
      <div class="col-xs-3">
        <%= f.label :first_name, 'First Name' %><br>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
      <div class="col-xs-3">
        <%= f.label :middle_name, 'Middle Name' %><br>
        <%= f.text_field :middle_name, class: 'form-control' %>
      </div>
      <div class="col-xs-3">
        <%= f.label :last_name, 'Last Name' %><br>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
      <div class="col-xs-3">
        <%= f.label :banner_id, 'Banner ID' %><br>
        <%= f.text_field :banner_id, class: 'form-control' %>
      </div>
      <div class="col-xs-3">
        <%= f.label :study_stage, 'Study Stage' %><br>
        <%= f.text_field :study_stage, class: 'form-control'  %>
      </div>
      <div class="col-xs-3">
        <%= f.label :expected_graduation, 'Expected Graduation Date' %><br>
        <%= f.date_select :expected_graduation, :start_year => Date.today.year, :discard_day => true, :order => [:year, :month], :include_blank => true, :with_css_classes => true %>
      </div>
      <div class="col-xs-3"
        <%= f.label :support_source, 'Support Source' %><br>
        <%= f.text_field :support_source, class: 'form-control' %>
      </div>
      <div class="col-xs-3"
        <%= f.label :placement %><br>
        <%= f.text_field :placement, class: 'form-control' %>
      </div>
    </div>
  </div>
    <%= link_to_remove_association "Remove Mentee Info", f %>
</div>

app/views/reports/_outreach_activity_fields.html.erb
<div class="nested-fields form-section container">

        <%= f.label :name, 'Outreach Activity' %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :description  %>
        <%= f.text_area :description, class: 'form-control' %>

    <%= link_to_remove_association "Remove Outreach Activity", f %>
</div>

app/views/reports/_professional_service_fields.html.erb
<div class="nested-fields form-section container">
        <%= f.label :title, 'Service Title' %>
        <%= f.text_field :title, class: 'form-control' %>

        <%= f.label :description  %>
        <%= f.text_area :description, class: 'form-control' %>

    <%= link_to_remove_association "Remove Professional Service Info", f %>
</div>

app/views/reports/_publication_fields.html.erb
<div class="nested-fields form-section container">

        <%= f.label :publication_type, 'Activity/Publication Type' %>
        <%= f.text_field :publication_type, class: 'form-control' %>
        
        <%= f.label :body, 'Text' %> <small>This should be a full citation for this publication</small>
        <%= f.text_area  :body, class: 'form-control' %>
       
        <%= f.label :url %>
        <%= f.text_area :url, class: 'form-control' %>


    <%= link_to_remove_association "Remove Publication Info", f %>
</div>

app/views/reports/_report.html.erb
<p>
    <strong>Report Year:</strong>
    <%= report.report_year %>
</p>


<%= link_to 'Show', person_report_path(@person, report), class: "btn btn-info" %>
<%= link_to 'Edit', edit_person_report_path(@person, report), class: "btn btn-warning" %>
<%= link_to 'Delete', person_report_path(@person, report), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to "Download Pdf", get_report_person_report_path(@person, report) %><br>
-----------------------------------------<br>

app/views/reports/_report_diverse.html.erb
<div class="container">
  <br/>
  <br/>
  <div class="row">
    <div class="col-sm-3">
      <strong>Calendar Year:</strong>
    </div>
    <div class="col-sm-9">
      <%= @report.report_year.strftime("%Y") %>
    </div>

  </div>
  <div class="row">
    <div class="col-sm-3">
      <strong>Faculty Name:</strong>
    </div>
    <div class="col-sm-9">
      <%= "#{@person.first_name} #{@person.last_name}" %>
    </div>

  </div>
  <div class="row">
    <div class="col-sm-3">
      <strong>Department:</strong>
    </div>
    <div class="col-sm-9">
      <%= @report.department %>
    </div>
  </div>
</div> 
<br/>
<h3>Scholarship</h3>
<hr class="faded"/>
<% @publications.each do |publication| %>
    <p>
        <%= publication.body %>
    </p>

<hr/>
<% end %>
    
<h3>Courses</h3>
<hr class="faded"/>
<% @courses.each do |course| %>
    <p>
        <strong>Year:</strong>
        <%= course.year.strftime("%Y") %>
    </p>
    <p>
        <strong>Semester:</strong>
        <%= course.semester %>
    </p>
    <p>
        <strong>Course Number:</strong>
        <%= course.course_number %>
    </p>
    <p>
        <strong>Course Title:</strong>
        <%= course.course_title %>
    </p>
    <p>
        <strong>Number Enrolled:</strong>
        <%= course.enrollment %>
    </p>
    <p>
        <strong>Evaluation Results:</strong>
        <%= course.evaluation_results %>
    </p>
    <p>
        <strong>Taught Course:</strong>
        <%= course.taught? ? 'Yes' : 'No' %>
    </p>

<hr/>
<% end %>

<h3>Professional Service</h3>
<hr class="faded"/>
<% @professional_services.each do |professional_service| %>
    <p>
        <strong>Activity:</strong>
        <%= professional_service.title %>
    </p>
    <p>
        <strong>Description:</strong>
        <%= professional_service.description %>
    </p>

<hr/>
<% end %>

<h3>University Service</h3>
<hr class="faded"/>
<% @university_services.each do |university_service| %>
    <p>
        <strong>Position:</strong>
        <%= university_service.position %>
    </p>
    <p>
        <strong>Description:</strong>
        <%= university_service.description %>
    </p>

<hr/>
<% end %>

<h3>Outreach Activities</h3>
<hr class="faded"/>
<% @outreach_activities.each do |outreach_activity| %>
    <p>
        <strong>Activity:</strong>
        <%= outreach_activity.name %>
    </p>
    <p>
        <strong>Description:</strong>
        <%= outreach_activity.description %>
    </p>

<hr/>
<% end %>
<% if (@grants.size > 0) %>
<h3>Grants</h3>
<hr class="faded"/>
<% end %>
<% @grants.each do |grant| %>
    <p>
        <strong>Grant Title:</strong>
        <%= grant.title %>
    </p>
    <p>
        <strong>Status:</strong>
        <%= grant.status %>
    </p>
    <p>
        <strong>Duration:</strong>
        <%= grant.duration %>
    </p>
    <p>
        <strong>Total Funding:</strong>
        <%= grant.total_funding %>
    </p>
    <p>
        <strong>UNM Portion:</strong>
        <%= grant.unm_portion %>
    </p>
    <p>
        <strong>Local College:</strong>
        <%= grant.granscol %>
    </p>
    <p>
        <strong>Local College Portion:</strong>
        <%= grant.soe_portion %>
    </p>

<hr/>
<% end %>

<h3>Research Mentoring</h3>
<hr class="faded"/>
<% @mentees.each do |mentee| %>
    <p>
        <strong>Name:</strong>
        <%= mentee.first_name + ' ' + mentee.last_name %>
    </p>
    <p>
        <strong>Type:</strong>
        <%= mentee.mentee_type.titleize %>
    </p>
    <p>
        <strong>Study Stage:</strong>
        <%= mentee.study_stage %>
    </p>
    <p>
        <strong>Expected Graduation Date:</strong>
        <%= mentee.expected_graduation.strftime("%B %Y") %>
    </p>
    <p>
        <strong>Support Source:</strong>
        <%= mentee.support_source %>
    </p>
    <p>
        <strong>Placement:</strong>
        <%= mentee.placement %>
    </p>

<hr/>
<% end %>

<div class="container">
    <table class="table table-condensed">
        <tr>
            <td><h3>Self Evaluation:</h3></td>
            <td><%= @report.self_evaluation_text %></td>
        </tr>
        <tr>
            <td><h3>Future Plans:</h3></td>
            <td><%= @report.future_plans_text %></td>
        </tr>
   </table>
</div>


<%= link_to 'Edit', edit_person_report_path(@person, @report) %>
<%= link_to 'Delete', person_report_path(@person, @report), method: :delete, data: { confirm: 'Are you sure?' } %><br>

app/views/reports/_university_service_fields.html.erb
<div class="nested-fields form-section container">
    <p>
        <%= f.label :title, 'University   Service Position' %><br>
        <%= f.text_field :position, class: 'form-control' %>
    </p>
    <p>
        <%= f.label :description  %><br>
        <%= f.text_area :description, class: 'form-control' %>
    </p>
    <%= link_to_remove_association "Remove University Service Position", f %>
</div>

app/views/reports/edit.html.erb
<p>
    <strong>First Name:</strong>
    <%= @person.first_name %>
    <strong>Last Name:</strong>
    <%= @person.last_name %>
</p>


<%= render 'form' %>

<%= link_to 'Cancel', person_reports_path(current_user, @report), class: "btn btn-warning btn-md" %>

app/views/reports/new.html.erb
<h1>Create New Annual Evaluation Open Period</h1>
<% if current_user.has_role? :department_admin, @department %>
  
  <div id="wrapper">
    <li style="margin-top: 20px">
      <input type="checkbox" name="all" id="all" checked=true /><label for='all'>All</label>
      <ul class="department-person-list">
      <% @department.people.each do |person| %>
        <li><input type="checkbox" name="selected[]" id= <%= 'box_' + person.banner_id %> value=<%= person.banner_id%>  checked=true /><label for=<%= 'box_' + person.banner_id %> /> <%= person.last_name + ', ' + person.first_name %></label></li>
      <% end %>
      </ul>
    </li>
  </div>
<% end %>
<%= link_to 'Cancel', person_reports_path(@person), class: "btn btn-warning btn-md" %>
<script>
$(document).ready(function(){
  $('input[name="all"],input[name="title"]').bind('click', function(){
    var status = $(this).is(':checked');
    $('input[type="checkbox"]', $(this).parent('li')).prop('checked', status);
  });
});
</script>

app/views/reports/newopenwindow.html.erb
<h1>Create New Annual Evaluation Open Period</h1>
<% if current_user.has_role? :department_admin, @department %>
  <fieldset class="form-group">
   <p>Select people to create report for:
    <ul style="list-style: none;">
      <%= form_tag reports_new_path do %>


        <div class="form-check">
          <input type="checkbox" name="checkAll" id="checkAll" checked=true /><label for='all'><h3>All People</h3></label>
        </div>
        <%= collection_check_boxes(nil, :people_ids, @department.people.all, :id, :full_name_reversed, include_hidden: false) do |cb| %>
            <li><%= cb.label class: 'form-check-label' do %>
              <%= cb.check_box(class: "form-check-input", checked: true) %>
              <%= cb.text %></li>
            <% end %>
        <% end %>
        <div class="col-md-5" id="datepicker-container">
          <br><p>Select window open and close date:
          <div class="input-daterange input-group" id="datepicker">
            <input type="text" class="input-sm form-control" name="start" />
            <span class="input-group-addon">to</span>
            <input type="text" class="input-sm form-control" name="end" />
          </div>
        </div>
      <%= submit_tag "Create", class: "btn btn-primary" %>
      <%= link_to 'Cancel', person_reports_path(@person), class: "btn btn-warning btn-md" %>
      <% end %>
    </ul>
  </fieldset>

<% end %>
<script>
      $('#datepicker-container .input-daterange').datepicker({
        format: 'yyyy-mm-dd'
    });
</script>

<script>
$("#checkAll").change(function () {
    $("input:checkbox").prop('checked', $(this).prop("checked"));
});
</script>

app/views/reports/show.html.erb
<div class="heading">
<h2>Annual Faculty Activity Report</h2>
<h4><%= @college.name %></h4>
<h4>University of New Mexico</h4>
</div>
<%= render 'report_diverse' %>
<br>
<%= link_to 'Back', person_reports_path(current_user), class: "btn btn-info btn-md" %>