config/routes.rb
Rails.application.routes.draw do

    resources :people do
    
      collection do
         get 'get_departments', to: "people#get_departments"
      end
        resources :reports do
            member do
              get 'get_report' => 'reports#gen_pdf'
            end
            resources :courses do
            end
        end
    end


    resources :colleges do
      resources :departments
    end
    get '/unauthorized' => 'application#unauthorized'
    root 'welcome#index'

    post '/usersearch/' => 'people#usersearch'
    post '/makeadmin' => 'people#makeadmin'
    post '/revokeadmin' => 'people#revokeadmin'
    get '/reports/new' => 'reports#newopenwindow'
    post '/reports/new' => 'reports#createopenwindow'

	  get '/authorize' => 'application#authorize'
    delete '/logout' => 'application#logout'
end

app/views/layouts/_header.html.erb
<!-- Header -->
<header id="header">
  <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
    <a class="navbar-brand" href="/">
      <%= image_tag('unm_logo.png', {height: '25px'}) %>
      Faculty Evaluation
    </a>
    <ul class="nav navbar-nav" style="float:left">
      <% if current_user %>
      <li class="nav-item">
        <a class="nav-item nav-link" href="<%= person_reports_path(current_user) %>">Evaluation Submissions</a>
      </li>

      <% if current_user.has_role? :global_admin %>
        <li class="nav-item">
          <a class="nav-item nav-link" href="<%= colleges_url %>">Colleges</a>
        </li>
      <% end %>
      <% if current_user.has_role? :department_admin, :any %>
        <li class="nav-item">
        <a class="nav-item nav-link" href="<%= department_url %>">Department</a>
        </li>
      <% end %>
      <% if current_user.has_role? :department_admin, @college %>
         <li class="nav-item dropdown"><a class="nav-item nav-link dropdown-toggle" data-toggle="dropdown" href="#"><%= @college.name %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <% @college.departments.each do |department| %>
                <li><a href="<%= college_department_url(@college,department) %>"><%= department.name %></a></li>
              <% end %>
            </ul>
         </li>
         <% end %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right" style="float: right">

      <li class="nav-item">
        <span class="navbar-text"><i class="fa fa-user" aria-hidden="true"></i> <%= current_user ? current_user.first_name : 'Unknown user' %></span>
      </li>
      <li class="nav-item">
        <%= link_to('/logout', method: :delete,  class: 'nav-item nav-link' ) do %><i class="fa fa-sign-out" aria-hidden="true"></i>Logout <% end %>
      </li>
    </ul>

  </nav>
</header>
<!-- End Header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UNM Faculty Evaluations</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div id="flash">
      <% flash.each do |key, value| %>
        <% if flash[:alert] %>
          <div class="alert alert-<%= key %>" style="margin-left:1em;background-color:#f2dede;color:a94442;border-color:ebccd1;padding:15px;margin-bottom:20px;border:1px solid transparent;border-radius:4px">
            <%= value %>
            <% flash[key] = nil #set to nil in case the flash was set without a following redirect %>
          </div>
        <% end %>
        <% if flash[:notice] %>
          <div class="notice notice-<%= key %>" style="margin-left:1em;background-color:#dff0d8;color:3c763d;border-color:d6e9c6;padding:15px;margin-bottom:20px;border:1px solid transparent;border-radius:4px">
          <%= value %>
            <% flash[key] = nil #set to nil in case the flash was set without a following redirect %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div id="app" class="container">
      <%= yield %> 
    </div>

  <script>
  </script>
  </body>


</html>